module.exports = {
  // CREATE_STAGED_PROPERTY: "CREATE_STAGED_PROPERTY",
  PROPERTIES_RECEIVED: "PROPERTIES_RECEIVED",
  PROPERTY_RECEIVED: "PROPERTY_RECEIVED",
  PROPERTY_REMOVED: "PROPERTY_REMOVED",
  STAGE_PROPERTY: "STAGE_PROPERTY"
};
